version: "2.2"
networks:
  rasmo-network:
services:
  nuvy-postgres:
    image: postgres:14.6
    restart: unless-stopped
    container_name: nuvy-postgres
    networks:
      - rasmo-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./database/data/postgresql:/var/lib/postgresql/data
      - ./database/initdb/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d nuvy -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5